services:
  - type: web
    name: django-backend
    env: python
    plan: free
    region: frankfurt 
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn newproject.wsgi
    rootDir: server/newproject
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: newproject.settings
      - key: PYTHON_VERSION
        value: 3.11.11
